/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as marketplaceSol from "./Marketplace.sol";
export type { marketplaceSol };
export type { CloudNFT } from "./CloudNFT";
