/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as marketplaceSol from "./Marketplace.sol";
export { CloudNFT__factory } from "./CloudNFT__factory";
